
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - tanzukubernetesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - tanzukubernetesclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmware.com
  resources:
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmware.com
  resources:
  - virtualnetworks/status
  verbs:
  - get
  - patch
  - update
